// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/trussle/courier/pkg/queue (interfaces: Queue,Segment)

package mocks

import (
	queue "github.com/trussle/courier/pkg/queue"
	uuid "github.com/trussle/courier/pkg/uuid"
	gomock "github.com/golang/mock/gomock"
)

// MockQueue is a mock of Queue interface
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
}

// MockQueueMockRecorder is the mock recorder for MockQueue
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return _m.recorder
}

// Dequeue mocks base method
func (_m *MockQueue) Dequeue() (queue.Segment, error) {
	ret := _m.ctrl.Call(_m, "Dequeue")
	ret0, _ := ret[0].(queue.Segment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dequeue indicates an expected call of Dequeue
func (_mr *MockQueueMockRecorder) Dequeue() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Dequeue")
}

// Enqueue mocks base method
func (_m *MockQueue) Enqueue(_param0 queue.Record) error {
	ret := _m.ctrl.Call(_m, "Enqueue", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue
func (_mr *MockQueueMockRecorder) Enqueue(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Enqueue", arg0)
}

// Reset mocks base method
func (_m *MockQueue) Reset() error {
	ret := _m.ctrl.Call(_m, "Reset")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reset indicates an expected call of Reset
func (_mr *MockQueueMockRecorder) Reset() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Reset")
}

// MockSegment is a mock of Segment interface
type MockSegment struct {
	ctrl     *gomock.Controller
	recorder *MockSegmentMockRecorder
}

// MockSegmentMockRecorder is the mock recorder for MockSegment
type MockSegmentMockRecorder struct {
	mock *MockSegment
}

// NewMockSegment creates a new mock instance
func NewMockSegment(ctrl *gomock.Controller) *MockSegment {
	mock := &MockSegment{ctrl: ctrl}
	mock.recorder = &MockSegmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockSegment) EXPECT() *MockSegmentMockRecorder {
	return _m.recorder
}

// Commit mocks base method
func (_m *MockSegment) Commit(_param0 []uuid.UUID) (queue.Result, error) {
	ret := _m.ctrl.Call(_m, "Commit", _param0)
	ret0, _ := ret[0].(queue.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit
func (_mr *MockSegmentMockRecorder) Commit(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Commit", arg0)
}

// Failed mocks base method
func (_m *MockSegment) Failed(_param0 []uuid.UUID) (queue.Result, error) {
	ret := _m.ctrl.Call(_m, "Failed", _param0)
	ret0, _ := ret[0].(queue.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Failed indicates an expected call of Failed
func (_mr *MockSegmentMockRecorder) Failed(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Failed", arg0)
}

// ID mocks base method
func (_m *MockSegment) ID() uuid.UUID {
	ret := _m.ctrl.Call(_m, "ID")
	ret0, _ := ret[0].(uuid.UUID)
	return ret0
}

// ID indicates an expected call of ID
func (_mr *MockSegmentMockRecorder) ID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ID")
}

// Size mocks base method
func (_m *MockSegment) Size() int {
	ret := _m.ctrl.Call(_m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size
func (_mr *MockSegmentMockRecorder) Size() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Size")
}

// Walk mocks base method
func (_m *MockSegment) Walk(_param0 func(queue.Record) error) error {
	ret := _m.ctrl.Call(_m, "Walk", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Walk indicates an expected call of Walk
func (_mr *MockSegmentMockRecorder) Walk(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Walk", arg0)
}
